// Public JS API for @babashka/cli, compiled from src/babashka/cli.cljc by squint.
// Friendly camelCase names are the documented surface; the squint-compiled names
// (parse_opts, spec__GT_opts, ...) are re-exported too for direct interop.
import {
  parse_opts,
  parse_opts_STAR_,
  parse_args,
  parse_cmds,
  coerce,
  coerce_opts,
  auto_coerce,
  parse_keyword,
  validate_opts,
  apply_defaults,
  spec__GT_opts,
  merge_opts,
  dispatch,
  format_opts,
  format_table,
  opts__GT_table,
  table__GT_tree,
  format_command_help,
  format_command_error,
  default_width_fn,
  _STAR_exit_fn_STAR_,
} from './js/babashka/cli.mjs';

export {
  // squint names
  parse_opts,
  parse_opts_STAR_,
  parse_args,
  parse_cmds,
  coerce,
  coerce_opts,
  auto_coerce,
  parse_keyword,
  validate_opts,
  apply_defaults,
  spec__GT_opts,
  merge_opts,
  dispatch,
  format_opts,
  format_table,
  opts__GT_table,
  table__GT_tree,
  format_command_help,
  format_command_error,
  default_width_fn,
  _STAR_exit_fn_STAR_,
  // friendly camelCase aliases
  parse_opts as parseOpts,
  parse_opts_STAR_ as parseOptsRaw,
  parse_args as parseArgs,
  parse_cmds as parseCmds,
  coerce_opts as coerceOpts,
  auto_coerce as autoCoerce,
  parse_keyword as parseKeyword,
  validate_opts as validateOpts,
  apply_defaults as applyDefaults,
  spec__GT_opts as specToOpts,
  merge_opts as mergeOpts,
  format_opts as formatOpts,
  format_table as formatTable,
  opts__GT_table as optsToTable,
  table__GT_tree as tableToTree,
  format_command_help as formatCommandHelp,
  format_command_error as formatCommandError,
  default_width_fn as defaultWidthFn,
};
